[package]
name = "asherpa"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.23", default-features = false, features = [ "rustls-tls" ] }

[dev-dependencies]
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = ["rt", "macros"] }
