[project]
name = "asherpa"
version = "0.0.1"
description = "Asynchronous download of support data"
authors = ["Guilherme Castelao <guilherme@castelao.net>", "Luiz Irber <github@luizirber.org>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
rust = ">=1.79.0,<1.80"
compilers = ">=1.7.0,<1.8"
