name: Rust checks

on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: '17 5 * * 5'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
